# This is included from the find modules generated by Conan. It creates
# different targets.
function(create_target_from_conan_name cmake_name conan_name)
    add_library(${cmake_name} INTERFACE IMPORTED)

    if(${conan_name}_INCLUDE_DIRS)
        set_target_properties(${cmake_name} PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${${conan_name}_INCLUDE_DIRS}")
    endif()
    set_property(TARGET ${cmake_name} PROPERTY INTERFACE_LINK_LIBRARIES
                 "${${conan_name}_LIBRARIES_TARGETS};${${conan_name}_LINKER_FLAGS_LIST}")
    set_property(TARGET ${cmake_name} PROPERTY INTERFACE_COMPILE_DEFINITIONS
                 ${${conan_name}_COMPILE_DEFINITIONS})
    set_property(TARGET ${cmake_name} PROPERTY INTERFACE_COMPILE_OPTIONS
                 "${${conan_name}_COMPILE_OPTIONS_LIST}")
endfunction()


create_target_from_conan_name(lp3::main lp3-main)
